FEDERATION_SERVER="https://api.stellar.org/federation" 

ACCOUNTS=
[ 
"GAAZODIX4SN7FNKOKN2C4HOYOUUE7H7S6V66GEE2V5LU6D4Y3ZONTEST", 
"GAKX6TVK3GWD3UFD7S52JG6FEXWGHRBMIZTMBRI33FJCU56ZZ6KYTEST", 
"GCPIFGDK3PQUTMLOR4KPMILYFS3S2GIKFCYEWHANRZOWSIWDQ5TUTEST", 
"GBEO2R6KTR6QBBWBJ26QXBTJUR24OEVZHWRCHDDMLTVUCF2MA5TVTEST", 
"GD5VN6CCHEZF2P5M67JS3W544ERROOWAWACFWOPYUOOJNX3PV5VGTEST", 
"GB6VEHESOY2C3DZ7GUGEZUEXPIWUAMKILDHQCZ5UTCIREYUPUGBCTEST" 
] 

[DOCUMENTATION] 
ORG_NAME="TESTNET PROJECT" 
ORG_URL="https://test.owaow.com" 
ORG_LOGO="https://test.owaow.com/logo/345x345.svg" 

[[CURRENCIES]] 
code="TEST" 
issuer="GAAZODIX4SN7FNKOKN2C4HOYOUUE7H7S6V66GEE2V5LU6D4Y3ZONTEST" 
status="live" 
name="TESTNET" 
desc="TESTNET PROJECT (Asset Code : TEST) is a Supporting Project of Stellar Lumens (XLM) Test Net on Public Live Network." 
display_decimals=7 
image="https://test.owaow.com/logo/64x64.svg" 
